[package]
name = "gw-proxy-recrypt"
version = "0.1.0"
edition = "2021"

[dependencies]
recrypt="0.13.1"
serde_json="1.0.127"
pad = "0.1.6"
bincode = "1.3.3"
env_logger = "0.11.4"
log = "0.4.21"
solana-sdk = "2.0.8"